const NSL_LEADS_KEY='nsl_leads';
const phone='5037601402';
const serviceOptions={
  Automotive:['Car lockout','Lost car key replacement','Spare key duplication','Transponder key programming','Smart key / proximity key programming','Push-to-start key programming','Key fob replacement','Broken key extraction','Ignition repair','Ignition replacement','Door lock repair','Trunk unlock','Rekeying vehicle locks','ECU / immobilizer programming','All-keys-lost programming','Emergency roadside locksmith service'],
  Residential:['House lockout','Lock rekeying','Lock installation','Deadbolt installation','Smart lock installation','Lock repair','Mailbox lock','Sliding door lock','Patio door lock','Gate lock','Key duplication','Master key system','High-security lock installation','Door knob / lever replacement','Peephole installation','Safe opening','Safe lock replacement','Tenant rekey service','Eviction locksmith service'],
  Commercial:['Commercial lock installation','Commercial rekeying','Master key system','Panic bar installation & repair','Exit device repair','Door closer','ADA hardware installation','Commercial lockout','Office rekey','Storefront door hardware','IC core system','High-security restricted key system','File cabinet lock','Desk lock','Access control system','Electric strike installation','Magnetic lock installation','Keypad lock','Proximity card system','Card/fob programming','Trilogy lock programming','Door alignment and adjustment','Continuous hinge','Door sweep & threshold','Door hardware replacement','Commercial door service']
};
function leads(){try{return JSON.parse(localStorage.getItem(NSL_LEADS_KEY)||'[]')}catch(e){return[]}}
function saveLead(lead){const list=leads();list.unshift(lead);localStorage.setItem(NSL_LEADS_KEY,JSON.stringify(list))}
function escapeHTML(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fillServices(){const category=document.querySelector('#category');const service=document.querySelector('#service');if(!category||!service)return;service.innerHTML='';(serviceOptions[category.value]||[]).forEach(item=>{const o=document.createElement('option');o.value=item;o.textContent=item;service.appendChild(o)})}
function bindLeadForm(){const form=document.querySelector('#leadForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());const lead={id:'NSL-'+Date.now(),createdAt:new Date().toLocaleString(),status:'New Lead',source:document.title,...data};saveLead(lead);const msg=`New locksmith lead: ${lead.name||'No name'} | ${lead.phone||'No phone'} | ${lead.category||''} | ${lead.service||''} | ${lead.urgency||''} | ${lead.address||''}`;const sms=document.querySelector('#smsLead');if(sms){sms.href='sms:'+phone+'?body='+encodeURIComponent(msg);sms.style.display='inline-flex'}const ok=document.querySelector('#formSuccess');if(ok){ok.style.display='block';ok.textContent='Lead saved in the demo dashboard. In production this will text/email the shop and push into the CRM.'}form.reset();fillServices()})}
function renderDashboard(){const mount=document.querySelector('#leadTable');if(!mount)return;const list=leads();if(!list.length){mount.innerHTML='<div class="card"><h3>No leads yet.</h3><p>Submit the booking form to test the lead system.</p></div>';return}mount.innerHTML='<div class="card"><h2>Saved leads</h2><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Time</th><th>Name</th><th>Phone</th><th>Service</th><th>Urgency</th><th>Address</th><th>Status</th></tr></thead><tbody>'+list.map(l=>`<tr><td>${escapeHTML(l.createdAt)}</td><td>${escapeHTML(l.name)}</td><td>${escapeHTML(l.phone)}</td><td>${escapeHTML(l.category)}<br><small>${escapeHTML(l.service)}</small></td><td>${escapeHTML(l.urgency)}</td><td>${escapeHTML(l.address)}</td><td>${escapeHTML(l.status)}</td></tr>`).join('')+'</tbody></table></div></div>'}
function exportLeads(){const list=leads();const headers=['id','createdAt','status','name','phone','email','category','service','urgency','address','vehicle','business','message','source'];const csv=[headers.join(','),...list.map(l=>headers.map(h=>'"'+String(l[h]||'').replaceAll('"','""')+'"').join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='northwest-security-lock-leads.csv';a.click();URL.revokeObjectURL(url)}
function clearLeads(){if(confirm('Clear demo leads?')){localStorage.removeItem(NSL_LEADS_KEY);renderDashboard()}}
document.addEventListener('DOMContentLoaded',()=>{fillServices();const c=document.querySelector('#category');if(c)c.addEventListener('change',fillServices);bindLeadForm();renderDashboard()});